const data = {
  products: [
    {
      
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 3500,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
     
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 2590,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
     
      name: 'Lacoste Free Shirt',
      slug: 'lacoste-free-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 2200,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {

      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 7800,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
     
      name: 'Puma Slim Pant',
      slug: 'puma-slim-pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 6500,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 1390,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'Louis Philippe Shirt',
      slug: 'louis-philippe-shirt',
      category: 'Shirts',
      image: '/images/p7.png',
      price: 4500,
      countInStock: 12,
      brand: 'Louis Philippe',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Van Heusen Shirt',
      slug: 'van-heusen-shirt',
      category: 'Shirts',
      image: '/images/p8.jpg',
      price: 4999,
      countInStock: 12,
      brand: 'Van Heusen',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'Raymond Shirt',
      slug: 'raymond-shirt',
      category: 'Shirts',
      image: '/images/p9.jpg',
      price: 4599,
      countInStock: 12,
      brand: 'Raymond',
      rating: 4.8,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'Pepe Jeans Black Shirt',
      slug: 'pepe-jeans-black-shirt',
      category: 'Shirts',
      image: '/images/p10.jpg',
      price: 3500,
      countInStock: 12,
      brand: 'Pepe Jeans',
      rating: 4.7,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Benetton Cool Shirt',
      slug: 'benetton-cool-shirt',
      category: 'Shirts',
      image: '/images/p11.jpg',
      price: 4500,
      countInStock: 12,
      brand: 'Benetton',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Van Heusen Black Pant',
      slug: 'van-heusen-black-pant',
      category: 'Pants',
      image: '/images/p12.jpg',
      price: 5500,
      countInStock: 12,
      brand: 'Van Heusen',
      rating: 4.8,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Louis Philippe Grey Pant',
      slug: 'louis-philippe-grey-pant',
      category: 'Pants',
      image: '/images/p13.jpg',
      price: 3999,
      countInStock: 12,
      brand: 'Louis Philippe',
      rating: 4.7,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Raymond Fit Pant',
      slug: 'raymond-fit-pant',
      category: 'Pants',
      image: '/images/p14.jpg',
      price: 3500,
      countInStock: 12,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Pepe Jeans Slim Fit Pant',
      slug: 'pepe-jeans-slim-fit-pant',
      category: 'Pants',
      image: '/images/p15.jpg',
      price: 4500,
      countInStock: 12,
      brand: 'Pepe Jeans',
      rating: 4.7,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Benetton Fit Pant',
      slug: 'benetton-fit-pant',
      category: 'Pants',
      image: '/images/p16.jpg',
      price: 5500,
      countInStock: 12,
      brand: 'Benetton',
      rating: 5.0,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Blackberry Fit Shirt',
      slug: 'blackberry-fit-shirt',
      category: 'Shirts',
      image: '/images/p17.jpg',
      price: 5100,
      countInStock: 12,
      brand: 'Blackberry',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'Blackberry Slim Fit Pant',
      slug: 'blackberry-slim-fit-pant',
      category: 'Pants',
      image: '/images/p18.jpg',
      price: 5500,
      countInStock: 12,
      brand: 'Blackberry',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
